### ISSUE TITLE
Screen Resolution 

### ISSUE THREAD

**Issue by CG-Rodriguez** [PascalKieslich/mousetrap-resources#1]
Hello,
I'm trying to run the tutorial experiment from the 2019 chapter, but I get an error message (" No video mode large enough for 1680x1050"). When I change to a lower resolution in the general properties of the experiment -- i.e. 1366 x 768 --  the buttons are not visible anymore.

Thanks!
Cristian R.

**Comment by CG-Rodriguez** [comment]
I just figured it out: when you change resolution, the sketchpads are resized. Then, you need to reset the position values of all the elements.

Basic OpenSesame stuff; still learning...

**Comment by PascalKieslich** [comment]
Hi Christian,
as you already correctly discovered and wrote in another message: sketchpads in OpenSesame use a pixel metric. So when you downsize the experiment resolution, they become smaller and content close to the borders of the sketchpad might not be displayed anymore.
Best,
Pascal
